config/routes.rb
Sol::Application.routes.draw do

  devise_for :users, controllers: { :registrations => :registrations, :sessions => :sessions }

  # new users only created by admin
  scope "/admin" do
    resources :users
  end

  resources :jobs
  resources :companies
  resources :people

  resources :addresses
  resources :states
  resources :towns
  resources :postcodes
  resources :countries

  resources :invoices
  resources :invoice_emails

  resources :reports
  resources :job_bag_emails

  resources :print_jobs
  resources :distribute_jobs
  resources :delivery_jobs

  resources :distribute_areas
  resources :delivery_locations

  resources :job_progresses
  
  resources :images
  resources :print_colours

  # for displaying email previews
  get 'invoice_mailer(/:action(/:id(.:format)))' => 'invoice_mailer#:action'

  root 'jobs#index'
end

app/models/distribute_area.rb
class DistributeArea < ActiveRecord::Base
	has_many :distribute_job
	has_many :image
	belongs_to :state

	before_create :activate!

	def summary
		output = self.name
		output << ' - ' << self.state.name unless self.state.blank?
		return output
	end

	def self.allActive
		return where(active: true)
	end

	def activate!
		self.active = true
	end
end

app/controllers/distribute_areas_controller.rb
class DistributeAreasController < ApplicationController

	def index
		@distribute_areas = DistributeArea.allActive

		if params[:id] != nil
			@distribute_area = DistributeArea.find(params[:id])
		elsif @distribute_areas.count != 0
			@distribute_area = DistributeArea.last
		else
			@distribute_area = nil
		end

		@sublayout = 'layouts/view'
	end

	def show
		@distribute_area = DistributeArea.find(params[:id])
    @distribute_areas = DistributeArea.allActive

		if params[:format] == 'string'
      render partial: 'show', layout: false
    
    else
      @sublayout = 'layouts/view'
      render 'index'
    end
	end

	def new
		australia = Country.where(name: 'Australia').first
		@states = State.where(country_id: australia.id)

		@sublayout = 'layouts/edit'
	end

	def create
		area = DistributeArea.new(post_params)
		area.save
		redirect_to distribute_area_path(area)
	end

	def edit
		australia = Country.where(name: 'Australia').first
		@states = State.where(country_id: australia.id)
		@distribute_area = DistributeArea.find(params[:id])
		
		@sublayout = 'layouts/edit'
	end

	def update
		area = DistributeArea.find(params[:id])
		area.update(post_params)
		redirect_to distribute_area_path(area)
	end

	def destroy
		area = DistributeArea.find(params[:id])
		area.destroy
		redirect_to distribute_areas_path
	end

	private
	def post_params
		params.require(:distribute_area).permit(
			:name,
			:description,
			:state_id
		)
	end

end

app/views/distribute_areas/_form.html.erb
<%# 
	distribute area form 
%>
<%
	if @distribute_area != nil
		delete_url = distribute_area_path(@distribute_area)
		form_url = distribute_area_path(@distribute_area)
		method = 'patch'

		delete_confirm = "Are you sure you want to permanently delete distribution area #{@distribute_area.name}!?"

	else
		delete_url = nil
		delete_confirm = nil
		form_url = distribute_areas_path
		method = 'post'
	end

	states_hash = {}
	@states.each {
		|state|
		states_hash[state.id] = state.name
	}

%>
<%= bs_form_for :distribute_area, url: form_url, method: method do |f| %>
	<%= f.text_field :name, 'Area Name', nil, required: true -%>
	<%= f.text_field :description, 'Description' -%>
	<%= f.static_drop_down :state_id, 'State', false, states_hash -%>
	<%= f.submit_well nil, distribute_areas_path, delete_url, delete_confirm -%>
<% end -%>

app/views/distribute_areas/_show.html.erb
<%#
	distribution area show
%>

<div class='panel panel-default main-panel'>
  <div class='panel-heading'>

    <h3 class='panel-title edit-heading'><%= "#{@distribute_area.name}" -%></h3>
    <%= link_to [:edit, @distribute_area], class: "glyphicon glyphicon-pencil edit-heading" do -%><% end -%>

  </div>
  <div class='panel-body'>

  	<h5><span class='name'>State:</span><%= @distribute_area.state.name if @distribute_area.state != nil -%></h5>

  	<h5><span class='name'>Description:</span><%= @distribute_area.description -%></h5>

  </div>
</div>

<br />

<%= render partial: 'tabs', locals: { show_add_button: true }  -%>

app/views/distribute_areas/_tabs.html.erb
<%#
	distribution area tabs

	optional locals: show_add_button
%>

<%
	if defined?(show_add_button) ==nil
		show_add_button = false
	end
%>

<ul class='nav nav-tabs nav-justified'>
  <li class='active'><a data-toggle='tab' href='#images-pane'>Images </a></li>
</ul>

<br />

<div class="tab-content">

  <div id='images-pane' class='tab-pane fade in active'>

    <% if @distribute_area.image != nil %>
      <% @distribute_area.image.each do |image| %>
        <% @image = image %>
        <%= render 'images/show_small' -%>
      <% end %>
    <% end %>

    <% if show_add_button %>
    	<form action='<%= new_image_path -%>' method='get'>
    		<input type='hidden' name='distribute_area_id' value='<%= @distribute_area.id -%>' />
    		<input type='submit' value='New Image' class='btn btn-default add-button' />
    	</form>
    <% end %>

  </div>
</div>

app/views/distribute_areas/edit.html.erb
<%#
	edit distribute area
%>

<% content_for :heading do %>

	<h2>Edit Distribution Area</h2>

<% end -%>

<% content_for :form do %>

	<%= render :partial => 'form'-%>

	<br />

	<%= render partial: 'tabs', locals: { show_add_button: true } -%>

<% end %>

app/views/distribute_areas/index.html.erb
<%#
  distribute areas index
%>

<%# object to get ID for JSON show in layouts/view %>
<% @object = @distribute_area %>

<% content_for :heading do %>

  <h2>Distribution Areas</h2>

<% end %>

<% content_for :master_list do %>

  <% @distribute_areas.each do |area| %>
    <a id='<%=area.id%>' data-url='<%=url_for :controller => 'distribute_areas', :action => 'show', :id => area.id, :format => 'string' %>' class="list-group-item">
      <h4 class="list-group-item-heading"><%= area.name -%></h4>
      <p class="list-group-item-text"></p>
    </a>
  <% end -%>
<% end %>


<% content_for :after_master_list do %>
  <%= button_to new_distribute_area_path, :class => 'btn btn-default', :method => 'get' do -%>
    Add Area
  <% end -%>

<% end %>

app/views/distribute_areas/new.html.erb
<%#
	new distribute area
%>

<% content_for :heading do %>

	<h2>New Distribution Area</h2>

<% end -%>

<% content_for :form do %>
	<%= render 'form' -%>
<% end %>