config/routes.rb
Sol::Application.routes.draw do

  devise_for :users, controllers: { :registrations => :registrations, :sessions => :sessions }

  # new users only created by admin
  scope "/admin" do
    resources :users
  end

  resources :jobs
  resources :companies
  resources :people

  resources :addresses
  resources :states
  resources :towns
  resources :postcodes
  resources :countries

  resources :invoices
  resources :invoice_emails

  resources :reports
  resources :job_bag_emails

  resources :print_jobs
  resources :distribute_jobs
  resources :delivery_jobs

  resources :distribute_areas
  resources :delivery_locations

  resources :job_progresses
  
  resources :images
  resources :print_colours

  # for displaying email previews
  get 'invoice_mailer(/:action(/:id(.:format)))' => 'invoice_mailer#:action'

  root 'jobs#index'
end

app/models/job.rb
class Job < ActiveRecord::Base
	
	REF_DATE_PART = Range.new(0, 1)
	REF_NUM_PART = Range.new(3, 6)

	belongs_to :company  # i.e. client
	belongs_to :person  # i.e. client contact

	has_one :print_job
	has_many :distribute_job

	has_many :invoice
	has_many :job_progress

	before_create :new_ref!
	before_create :new_status!

	accepts_nested_attributes_for :distribute_job, allow_destroy: true 
	accepts_nested_attributes_for :print_job

	# ref = yy-nnnn where nnnn is the number of jobs in the year
	# e.g. the 20th job of 2016 would be 16-0020
	def new_ref!
		year_str = Date.today.year.to_s[2..4]
		last_num = 1
		last_job = Job.select('*')
									.order('ref')
									.last
		if last_job != nil
			if last_job.ref[REF_DATE_PART] == year_str
				last_num = last_job.ref[REF_NUM_PART].to_i
			end
		end
		num_str = "%04d" % (last_num + 1)
		self.ref = "#{year_str}-#{num_str}"
	end

	# Sets the status to REQUEST RECEIVED
	def new_status!
		self.status = JobStatus::REQUEST_RECEIVED
	end

	def summary
		output = "#{self.name} - "
		output << self.is_distribute_only ? 'distribute only' : 'print and distribute'			 
		return output
	end

	# Returns all print items and distribution items as a flat array
	def subjobs
		subs = []
		subs.push(print_job) unless print_job == nil
		subs += distribute_job unless distribute_job == nil
		return subs
	end

	# Returns a hash { :amount, :gst, :total } from either the package_quote, or the totalled quote_amount from each subjob
	def totals
		amount = nil
		if self.is_package_deal
			amount = self.package_quote == nil ? 0 : self.package_quote
		else
			amount = 0.0
			self.subjobs.each {
				|sub|
				amount += sub.quote_amount == nil ? 0 : sub.quote_amount
			}
		end
		gst = amount * 0.1

		return {
			amount: amount,
			gst: gst,
			total: (amount + gst)
		}
	end

	# Returns an array of quote items for the job
	def quote_items

		items = []

		if is_package_deal
			description = "Package deal - #{name}"
			qty = 1
			amount = package_quote

			item = QuoteItem.new(description, qty, amount)
			items.push(item)

		else
			subjobs.each {
				|sub|

				if sub.is_a?(PrintJob)
					description = "Printing"
				elsif sub.is_a?(DistributeJob)
					description = "Distribution - #{sub.distribute_area.name}"
				end

				qty = sub.quantity
				amount = sub.quote_amount
						
				item = QuoteItem.new(description, qty, amount)
				items.push(item)
			}
		end
		return items
	end

	# returns all quotes
	def quotes
		return self.invoice.reject { |invoice| !invoice.is_quote }
	end

	# returns an error message for the first missing quote amount
	def missing_quotes
		if is_package_deal
			return package_quote.blank? ? 'Package quote amount missing' : nil

		elsif print_job
			return 'Print job quote amount missing' if print_job.quote_amount.blank?
		end

		msg = nil
		distribute_job.each {
			|dist|
			if dist.quote_amount.blank?
				msg = "Quote amount missing for #{dist.distribute_area.name} distribution job"
				break
			end
		}

		return msg
	end

	# returns each supplier's email address as an array
	def supplier_emails
		emails = []

		unless is_distribute_only
			if print_job.company
				if print_job.company.email.include?('@')
					emails.push(print_job.company.email)
				end
			end
		end

		distribute_job.each {
			|dist|
			if dist.company
				if dist.company.email.include?('@')
					emails.push(dist.company.email)
				end
			end
		}

		return emails.uniq
	end

	# returns all subjobs without a supplier email address
	def sub_jobs_missing_emails
		subjobs = []

		unless is_distribute_only
			if print_job.company
				unless print_job.company.email.include?('@')
					subjobs.push(print_job)
				end
			
			else
				subjobs.push(print_job)
			end
		end

		distribute_job.each {
			|dist|
			if dist.company
				unless dist.company.email.include?('@')
					subjobs.push(dist)
				end
			
			else
				subjobs.push(dist)
			end
		}

		return subjobs
	end

	def self.all_in_progress
		return Job.where(
			"status = '#{JobStatus::REQUEST_RECEIVED}' OR " +
			"status = '#{JobStatus::SENT_TO_PRINTERS}' OR " +
			"status = '#{JobStatus::PRINTING_DONE}' OR " +
			"status = '#{JobStatus::DISTRIBUTION_IN_PROGRESS}' OR " +
			"status = '#{JobStatus::QUOTE_SENT}' OR " +
			"status = '#{JobStatus::QUOTE_ACCEPTED}' OR " +
			"status = '#{JobStatus::QUOTE_REJECTED}'"
		).order(:ref)
	end

	def self.all_completed
		return Job.where(
			"status = '#{JobStatus::JOB_COMPLETED}' OR " + 
			"status = '#{JobStatus::JOB_CANCELLED}'"
		).order(:ref)
	end

	class QuoteItem 
		attr_reader :description, :qty, :amount
		def initialize(description, qty, amount)
			@description = description
			@qty = qty
			@amount = amount
		end
	end
	
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

	def index
		@filter = params[:filter]

		if @filter == 'completed'
			@jobs = Job.all_completed

		elsif @filter == 'in_progress'
			@jobs = Job.all_in_progress

		else
			@jobs = Job.all.order(:ref)
		end

		if params[:id] != nil
			@job = Job.find(params[:id])
		elsif @jobs.count > 0
			@job = @jobs.last
		else
			@job = nil
		end

		if params[:format] == 'json'
			@jobs.each {  # change job refs to HTML links... . .
				|job|
				job.ref = "<a href='#{jobs_path id: job.id}'>#{job.ref}</a>"
			}
			render json: @jobs, include: :print_job
		elsif params[:overview]			
			render :overview 
		else
			@sublayout = 'layouts/view'
		end
	end

	def show		
		@job = Job.find(params[:id])

		if params[:format] == 'json'
			respond_to do |format|
  			format.json  { render :json => @job.to_json(:include => [:company])}
			end
			
		elsif params[:format] == 'string'
			render partial: 'show', layout: false
		
		else
			@filter = params[:filter]

			if @filter == 'completed'
				@jobs = Job.all_completed

			elsif @filter == 'in_progress'
				@jobs = Job.all_in_progress

			else
				@jobs = Job.all.order(:ref)
			end

      @sublayout = 'layouts/view'
      render 'index'
		end
	end

	def new
		distribute_only = params[:distribute_only].to_i > 0
		@job = Job.new(is_distribute_only: distribute_only)

		unless @job.is_distribute_only
			@job.build_print_job
			@job.print_job.build_print_stock
			@job.print_job.build_print_product
			@job.print_job.build_print_size
		end

		@companies = Company.allByCompanyType(CompanyType::CLIENT)
		@delivery_locations = DeliveryLocation.allActive

		@stocks = PrintStock.all
		@sizes = PrintSize.all
		@products = PrintProduct.all

		@sublayout = 'layouts/edit'
	end

	def create
		@job = Job.new(post_params)

		# validate
		ok = true
		message = 'Job not saved - '

		if @job.is_package_deal && !@job.package_quote
			flash.now[:alert] = message + 'package quote amount missing'
			ok = false

		elsif @job.is_distribute_only && @job.distribute_job.empty?
			flash.now[:alert] = message + 'distribute-only jobs need at least one distribution job'
			ok = false

		elsif !@job.is_package_deal

			if !@job.is_distribute_only && !@job.print_job.quote_amount
				flash.now[:alert] = message + 'either set a package quote amount, or enter print, and all distribution job quote amounts'
				ok = false
				
			else
				@job.distribute_job.each {
					|dist_job|

					unless dist_job.quote_amount
						flash.now[:alert] = message + 'either set a package quote amount, or enter all distribution job quote amounts'
						ok = false
						break
					end
				}
			end			
		end

		unless ok
      @companies = Company.allByCompanyType(CompanyType::CLIENT)
      @delivery_locations = DeliveryLocation.allActive

      @stocks = PrintStock.all
      @sizes = PrintSize.all
      @products = PrintProduct.all

			@sublayout = 'layouts/edit'
			render :new
			return
		end
	  
	  unless @job.is_distribute_only
		  stock = @job.print_job.print_stock
			product = @job.print_job.print_product
			size = @job.print_job.print_size

	  	stock = @job.print_job.print_stock
			product = @job.print_job.print_product
			size = @job.print_job.print_size

	  	@job.print_job.print_stock = stock[:name].blank? ? nil : PrintStock.find_or_create_by(name: stock[:name])
			@job.print_job.print_product = product[:name].blank? ? nil : PrintProduct.find_or_create_by(name: product[:name])
			@job.print_job.print_size = size[:name].blank? ? nil : PrintSize.find_or_create_by(name: size[:name])
		end

		@job.save
    flash[:alert] = nil
		redirect_to new_invoice_path(job_id: @job.id, is_outgoing: false, is_quote: true)
	end

	def edit
    @job = Job.find(params[:id])
		@distribute_only = @job.is_distribute_only
    @companies = Company.allByCompanyType(CompanyType::CLIENT)
		@delivery_locations = DeliveryLocation.allActive

    @stocks = PrintStock.all
		@sizes = PrintSize.all
		@products = PrintProduct.all

		unless @job.is_distribute_only
			@job.print_job.build_print_stock unless @job.print_job.print_stock 
			@job.print_job.build_print_product unless @job.print_job.print_product
			@job.print_job.build_print_size unless @job.print_job.print_size
		end

		@edit_mode = 'true'
    @sublayout = 'layouts/edit'
  end

  def update
    job = Job.find(params[:id])
		prev_accepted_quote = job.accepted_quote
    job.assign_attributes(post_params)

		job_accepted =  !prev_accepted_quote && job.accepted_quote
		job.status = JobStatus::QUOTE_ACCEPTED if job_accepted

    unless job.is_distribute_only
	  	stock = job.print_job.print_stock || PrintStock.new
			product = job.print_job.print_product || PrintProduct.new
			size = job.print_job.print_size || PrintSize.new

	  	job.print_job.print_stock = stock[:name].blank? ? nil : PrintStock.find_or_create_by(name: stock[:name])
			job.print_job.print_product = product[:name].blank? ? nil : PrintProduct.find_or_create_by(name: product[:name])
			job.print_job.print_size = size[:name].blank? ? nil : PrintSize.find_or_create_by(name: size[:name])
		end

    job.save

    if job_accepted
    	redirect_to new_report_path(
    		job_id: job.id,
    		report_type: 'job_bag',
    		format: 'pdf',
    		email: true
  		)
  		return

		else
    	redirect_to action: 'show'
    	return
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to action: 'index', status: 303
  end

	private
	def post_params
		params.require(:job).permit(
			:name, 
			:request_received, 
			:company_id,
			:person_id,
			:is_package_deal,
			:is_distribute_only,
			:package_quote,
			:status,
			:accepted_quote,
			distribute_job_attributes: [
				'_destroy',
				:id,
				:distribute_area_id,
				:company_id,
				:campaign_start,
				:campaign_end,
				:notes,
				:quantity,
				:quote_amount
			],
			print_job_attributes: [
				:id,
				:date_due,
				:both_sides,
				:company_id,
				:quantity,
				:quote_amount,
				:notes,
				:delivery_location_id,
				print_stock_attributes: [ :id, :name ],
				print_size_attributes: [ :id, :name ],
				print_product_attributes: [ :id, :name ]
			]
		)
	end

end

app/views/jobs/_form.html.erb
<%#
	job form
%>
<%
	if !@job.new_record?
		delete_url = job_path(@job)
		form_url = job_path(@job)
		method = 'patch'
		delete_confirm = "Are you sure you want to permanently delete job #{@job.ref} - #{@job.name}!?"

		status_hash = {}
		JobStatus::ALL_STATUSES.each {
			|status|
			status_hash[status] = status
		}

	else
		delete_url = nil
		delete_confirm = nil
		form_url = jobs_path
		method = 'post'
		invoiceModalId = 'loading-xero-modal'
	end

%>
<%= bs_form_for @job, url: form_url, method: method, id: 'job-form' do |f| %>
	<%= f.text_field :name, 'Job Name', nil, required: true, placeholder: 'i.e. Big Day Out 1999' -%>
	<%= 
		f.dynamic_drop_down :company_id, 'Client',
			group_id: 'client-dropdown',
			url: companies_path(format: :json),
			next_dropdown: 'contact-dropdown',
			value_name: 'id',
			load_first: true
	-%>
	<%= 
		f.dynamic_drop_down :person_id, 'Contact Person',
			group_id: 'contact-dropdown',
			url: people_path(format: :json),
			param_name: 'company_id',
			value_name: 'id',
			text_name: 'summary'
	-%>
	<%= f.static_drop_down(:status, 'Job Status', false, status_hash, required: true) if !@job.new_record? -%>
	<%= f.date_picker :request_received, 'Request Received', nil, required: true -%>
	<%= f.check_box :is_package_deal, 'Package Deal?', nil, '', :data => { 'show-on-check' => '#job-quote-field', 'hide-on-check' => '.sub-quote-field' } -%>

	<div id='job-quote-field'>
		<%= f.text_field :package_quote, 'Package Quote Amount', nil, class: 'number' -%>
	</div>

	<% if !@job.is_distribute_only %>
		<%= tag :hr, class: 'form-divider' -%>
		<%= render partial: 'print_jobs/sub_form', locals: { form: f, print_job: @job.print_job } -%>
	<% end %>
	
	<%= tag :hr, class: 'form-divider' -%>
	<%= render partial: 'distribute_jobs/multi_form', locals: { form: f, job: @job } -%>

	<%= f.hidden_field :is_distribute_only -%>
	<%= f.submit_well nil, root_path, delete_url, delete_confirm -%>
<% end -%>

<% if @job.new_record? %>
	<%= loading_modal('Loading', 'Saving Job and Talking to Xero', id: invoiceModalId) -%>

	<script type="text/javascript">
		$('form').submit(function () {
			if ($(this).valid()) {
				$('#<%= invoiceModalId -%>').modal('show'); 
			}
		});
	</script>

<% end %>

app/views/jobs/_quotes_modal.html.erb
<%#
  Required locals:
    modal_id
%>
<%
  quotes_hash = {}
  @job.quotes.each {
    |quote|
    quotes_hash[quote.id] = quote.summary
  }
%>
<div class='modal fade' id='<%= modal_id -%>' tabindex='-1' role='dialog' aria-hidden='true'>
  <div class='modal-dialog'>
    <div class='modal-content'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal' aria-hidden='true'>&times;</button>
        <h4 class='modal-title'>Quote Accepted</h4>
      </div>
      <div class='modal-body'>
        <h3>Which Quote Was Accepted?</h3>

        <%= bs_form_for @job, url: job_path(@job), method: :patch, html: { id: 'accept-quote-form' } do |f| %>
          <%= f.static_drop_down :accepted_quote, 'Accepted Quote', false, quotes_hash, required: true, id: 'quote-dropdown' -%>
        <% end %>

      </div>
      <div class='modal-footer'>
        <button type='button' class='btn btn-default' data-dismiss='modal'>Cancel</button>
        <button id='save-quote-accepted' type='button' class='btn btn-primary'>Save</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

  $('#<%= modal_id -%>').on('show.modal.bs', function () {
    partialLoadDropdowns(this, true);
  });

  $('#save-quote-accepted').click(function () {
    console.log($('#accept-quote-form'));
    $('#accept-quote-form').submit();
  });

</script>

app/views/jobs/_show.html.erb
<%#
	job show
%>
<%
  quote_accepted_modal_id = 'quote-accepted-modal';
%>
<div class='panel panel-default main-panel'>

  <div class='panel-heading'>
    <h3 class='panel-title edit-heading'><%= "#{@job.name} - #{@job.status}" -%></h3>
    <%= link_to [:edit, @job], class: "glyphicon glyphicon-pencil edit-heading" do -%><% end -%>
  </div>

  <div class='panel-body'>
    <%= display_basic 'Reference', @job.ref -%>
    <%= display_basic 'Client', @job.company.name unless @job.company.blank? -%>
    <%= display_basic 'Contact', @job.person.summary unless @job.person.blank? -%>    
    <%= display_date 'Job Request Date', @job.request_received -%>
    <%= display_money 'Package Quote', @job.package_quote if @job.is_package_deal -%>

    <% unless @job.is_distribute_only %>
      <hr>
      <% @print_job = @job.print_job %>
      <h4>Print Job</h4>
      <%= render partial: 'print_jobs/show_fields' -%>
    <% end %>

    <% @job.distribute_job.each_with_index do |dist_job, i| %>
      <% @distribute_job = dist_job %>
      <hr>
      <h4>Distribute Job <%= i + 1 if @job.distribute_job.count > 1 -%></h4>
      <%= render partial: 'distribute_jobs/show_fields' -%>
    <% end %>
  </div>

  <div class='panel-footer'>

    <% unless @job.accepted_quote || @job.quotes.empty? %>
      <div class="btn-group">
        <button id='quote-accepted-button' class='btn btn-sm'>Quote Accepted</button>
      </div>
    <% end %>

    <% unless @job.job_progress.blank? %>
      <%= form_for :report, method: :get, url: new_report_path, html: { class: 'inline-form' } do |f| %>
        <div class="btn-group">
          <button type='submit' class='btn btn-sm dropdown-toggle'>Progress Report</button>
          <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <ul class="dropdown-menu text-center" role="menu">
            <li><a data-format='pdf' data-input='progress-format'>PDF</a></li>
            <li><a data-format='odt' data-input='progress-format'>ODT</a></li>
          </ul>          
          <input type='hidden' name='job_id' value='<%= @job.id -%>' />
          <input type='hidden' name='report_type' value='progress' />
          <input id='progress-format' type='hidden' name='format' value='pdf' />
        </div>
      <% end %>
    <% end %>

    <%= form_for :report, method: :get, url: new_report_path, html: { class: 'inline-form' } do |f| %>
      <div class="btn-group">
        <button type='submit' class='btn btn-sm dropdown-toggle'>Job Bag</button>
        <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown">
          <span class="caret"></span>
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu text-center" role="menu">
          <li><a data-format='pdf' data-input='print-format'>PDF</a></li>
          <li><a data-format='odt' data-input='print-format'>ODT</a></li>
        </ul>
        <input type='hidden' name='job_id' value='<%= @job.id -%>' />
        <input type='hidden' name='report_type' value='job_bag' />
        <input id='print-format' type='hidden' name='format' value='pdf' />
      </div>
    <% end %>

  </div>
</div>

<br />

<%= render partial: 'tabs', locals: { show_add_button: true }  -%>

<% unless @job.quotes.empty? %>
  <%= render partial: 'quotes_modal', locals: { modal_id: quote_accepted_modal_id } -%>
<% end %>

<script type="text/javascript">
  $('document').ready (function() {

    // Handle report format dropdowns
    $('a[data-format]').click(function (clickEvent) {
      var link = $(clickEvent.currentTarget);
      var format = link.data('format');
      var inputField = $('#' + link.data('input'));

      inputField.val(format);

      console.log(format);
      console.log(inputField);

      inputField.parents('form').submit();

      // Set format back to default
      inputField.val('pdf');
    })

    // Handle quote accepted button click
    $('#quote-accepted-button').click(function () {
        $('#<%= quote_accepted_modal_id -%>').modal('show');
    });

  });
</script>

app/views/jobs/_tabs.html.erb
<%#
	job tabs

  optional locals: show_add_button
%>
<%
  if defined?(show_add_button) ==nil
    show_add_button = false
  end
  
  invoiceModalId = 'invoice-modal'  
%>
<ul id='job-tabs' class='nav nav-tabs nav-justified'>
  <% unless @job.is_distribute_only %>
    <li><a data-toggle='tab' href='#colours-pane'>Colours</a></li>
    <li><a data-toggle='tab' href='#images-pane'>Print Images </a></li>
  <% end %>
  <li><a data-toggle='tab' href='#invoices-pane'>Quotes</a></li>
  <li><a data-toggle='tab' href='#progress-pane'>Progress </a></li>
</ul>

<br />
<br />

<div class="tab-content">

  <% unless @job.is_distribute_only %>
    <% @print_job = @job.print_job %>
    
    <div id='colours-pane' class='tab-pane fade'>
      <% @job.print_job.print_colour.each do |print_colour| %>
        <% @print_colour = print_colour %>
        <%= render 'print_colours/show_small' -%>
      <% end %>

      <% if show_add_button %>
        <form action='<%= new_print_colour_path -%>' method='get'>
          <input type='hidden' name='print_job_id' value='<%= @job.print_job.id -%>' />
          <input type='submit' value='New Colour' class='btn btn-default add-button' />
        </form>
      <% end %>
    </div>

    <div id='images-pane' class='tab-pane fade'>
      <% @job.print_job.image.each do |image| %>
        <% @image = image %>
        <%= render 'images/show_small' -%>
      <% end %>

      <% if show_add_button %>
        <form action='<%= new_image_path -%>' method='get'>
          <input type='hidden' name='print_job_id' value='<%= @job.print_job.id -%>' />
          <input type='submit' value='New Image' class='btn btn-default add-button' />
        </form>
      <% end %>
    </div>
  <% end %>

  <div id='invoices-pane' class='tab-pane fade'>
    <% @job.invoice.each do |invoice| %>

      <%# display only outgoing invoices that are either non-invoiced quotes, or invoices %>
      <% if !invoice.is_outgoing && (invoice.is_quote && invoice.quote_invoice == nil ) || !invoice.is_quote %>
        <% @invoice = invoice %>
        <% is_accepted = @job.accepted_quote == @invoice.id %>
        <%= render partial: 'invoices/show_small', locals: { modal_id: invoiceModalId, is_accepted: is_accepted } -%>
      <% end %>    
    <% end %>

    <% if show_add_button %>
      <form action='<%= new_invoice_path -%>' method='get' class='add-invoice-form'>
        <input type='hidden' name='job_id' value='<%= @job.id -%>' />
        <input type='hidden' name='is_outgoing' value='false' />
        <input type='hidden' name='is_quote' value='true' />
        <input type='submit' value='New Quote' class='btn btn-default add-button' data-toggle='modal' data-target='#<%= invoiceModalId -%>' />
      </form>
    <% end %>
  </div>

  <div id='progress-pane' class='tab-pane fade'>
    <% @job.job_progress.each do |job_progress| %>
      <% @job_progress = job_progress %>
      <%= render partial: 'job_progresses/show_small' -%>
    <% end %>

    <% if show_add_button %>
      <form action='<%= new_job_progress_path -%>' method='get'>
        <input type='hidden' name='job_id' value='<%= @job.id -%>' />
        <input type='submit' value='New Progress Item' class='btn btn-default add-button' />
      </form>
    <% end %>
  </div>
</div>

<%# select the first tab %>
<script type="text/javascript">
  $('#job-tabs a:first').tab('show');
</script>

<%= loading_modal('New Invoice Loading', 'Talking to Xero', id: invoiceModalId) if show_add_button -%>

app/views/jobs/edit.html.erb
<%#
	edit job
%>
<% content_for :heading do %>
	<h2>Edit Job - <%= "#{@job.ref} - #{@job.name}" -%></h2>
<% end -%>
<% content_for :form do %>
	<%= render 'form' -%>
	<br />
	<%= render partial: 'tabs', locals: { show_add_button: true } -%>
<% end %>

app/views/jobs/index.html.erb
<%#
  job index
%>

<%# object to get ID for JSON show in layouts/view %>
<% 
  @object = @job
%>

<% content_for :heading do %>
  <h2>Jobs</h2>
<% end %>

<% content_for :master_list do %>

  <div class="btn-group" style='width:100%'>
    <button id='completed-button' type="button" class="btn btn-default" style='width:33.33%' data-filter='completed'>Completed</button>
    <button id='all-button'  type="button" class="btn btn-default active" style='width:33.33%' data-filter='all'>All</button>
    <button id='in-progress-button'  type="button" class="btn btn-default" style='width:33.33%' data-filter='in_progress'>In Progress</button>
  </div>

  <br />
  <br />

	<% @jobs.each do |job| %>
    <% heading = job.ref %>
    <% heading << ' - ' << date_fmt(job.request_received) unless job.request_received.blank? %>
		<a id='<%=job.id%>' data-url='<%=url_for :controller => 'jobs', :action => 'show', :id => job.id, :format => 'string' %>' class="list-group-item text-center">
			<h4 class="list-group-item-heading"><%= heading -%></h4>
    	<p class="list-group-item-text"><%= job.name -%></p>
		</a>
	<% end -%>
<% end %>


<% content_for :after_master_list do %>
  <div class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
      New Job
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to "Print + Distribute", new_job_path(distribute_only: 0) -%></li>
      <li><%= link_to "Distribute Only", new_job_path(distribute_only: 1) -%></li>
    </ul>
  </div>
<% end %>

<% content_for :js_start do %>
  <script type="text/javascript">

    $(document).ready(function(e) {

      //Make appropriate filter button active
      var activeButtonId = 
      <% if @filter == 'completed' %>
        'completed-button';
      <% elsif @filter == 'in_progress' %>
        'in-progress-button';
      <% else %>
        'all-button';
      <% end %>
      $('button[data-filter]').removeClass('active')
      $('#' + activeButtonId).addClass('active')

      //Handle filter buttons click
      $('button[data-filter]').click(function(e) {

        $('button[data-filter]').removeClass('active')
        $(e.target).addClass('active')

        var href = '<%= jobs_path -%>' + '?filter=' + $(e.target).attr('data-filter');
        window.location = href;
      });

    });

  </script>
<% end %>

app/views/jobs/new.html.erb
<%#
	new job
%>
<% content_for :heading do %>
	<% if @distribute_only %>
		<h2>New Distribute-Only Job</h2>
	<% else %>
		<h2>New Print and Distribute Job</h2>
	<% end -%>
<% end -%>
<% content_for :form do %>
	<%= render 'form' -%>
<% end %>