config/routes.rb
Sol::Application.routes.draw do

  devise_for :users, controllers: { :registrations => :registrations, :sessions => :sessions }

  # new users only created by admin
  scope "/admin" do
    resources :users
  end

  resources :jobs
  resources :companies
  resources :people

  resources :addresses
  resources :states
  resources :towns
  resources :postcodes
  resources :countries

  resources :invoices
  resources :invoice_emails

  resources :reports
  resources :job_bag_emails

  resources :print_jobs
  resources :distribute_jobs
  resources :delivery_jobs

  resources :distribute_areas
  resources :delivery_locations

  resources :job_progresses
  
  resources :images
  resources :print_colours

  # for displaying email previews
  get 'invoice_mailer(/:action(/:id(.:format)))' => 'invoice_mailer#:action'

  root 'jobs#index'
end

app/models/company.rb
class Company < ActiveRecord::Base

	has_one :address
	has_many :person

	before_create :activate!


	def self.allByCompanyType(company_type)
		return Company.all.where("company_type = '#{company_type}' AND active = TRUE").order('created_at DESC')
	end

	def self.lastByCompanyType(company_type)
		return Company.allByCompanyType(company_type).last
	end

	def activate!
		self.active = true
	end

	def summary
		return "#{self.company_type} - #{self.name}"
	end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index
    if params[:company_type] == nil
      @company_type = CompanyType::CLIENT
    else
      @company_type = params[:company_type]
    end

    @companies = Company.allByCompanyType(@company_type).order(:name)
    @company = Company.lastByCompanyType(@company_type)

    if params[:format] == 'json'
      render json: @companies

    else
      @sublayout = 'layouts/view'
    end
  end

  def show
  	@company = Company.find(params[:id])

		if params[:format] == 'json'
      render :json => @company.to_json(:include => [:person, :address])

		elsif params[:format] == 'string'
      if params[:company_type] == nil
        @companies = Company.where('active = TRUE').order(:name)
      else
        @companies = Company.allByCompanyType(params[:company_type])
      end
      render partial: 'show', layout: false
    
    else
      @company_type = @company.company_type
      @companies = Company.allByCompanyType(@company_type)

      @sublayout = 'layouts/view'
      render 'index'
    end
  end

  def new
    @company_type = params[:company_type]
  	@company_types = CompanyType::ALL_TYPES
    @countries = Country.all.order(:name);
    @country = Country.where(:name => 'Australia')
    
    @sublayout = 'layouts/edit'
  end

  def create
  	@company = Company.new(post_params)
		@company.save
		redirect_to company_path(@company)
  end

  def edit    
    @company_types = CompanyType::ALL_TYPES
    @countries = Country.all.order(:name);
    @country = Country.where(:name => 'Australia')

    @company = Company.find(params[:id])
    
    @sublayout = 'layouts/edit'
  end

  def update
    @company = Company.find(params[:id])
    @company.update(post_params)
    redirect_to action: 'show'
  end

  def destroy
    @company = Company.find(params[:id])
    @company.update(active: false)
    redirect_to action: 'index', status: 303, company_type: @company.company_type
  end

  private
	def post_params
		params.require(:company).permit(
      :name, 
      :abn, 
      :company_type, 
      :address_id,
      :phone,
      :fax,
      :email
    )
	end
end

app/views/companies/_form.html.erb
<%#
	company form
%>
<%
	if @company != nil
		delete_url = company_path(@company)
		form_url = company_path(@company)
		method = 'patch'
		delete_confirm = "Are you sure you want to permanently delete #{@company.company_type} #{@company.name}!?"		

	else
		delete_url = nil
		delete_confirm = nil
		form_url = companies_path
		method = 'post'
	end

	company_types_hash = {}
	@company_types.each {|type| company_types_hash[type] = type }

%>
<%= bs_form_for :company, url: form_url, method: method do |f| -%>
	<%= f.text_field :name, 'Company Name', nil, required: true -%>
	<%= f.static_drop_down :company_type, 'Company Type', false, company_types_hash, required: true -%>
	<%= f.text_field :abn, 'ABN' -%>
	<%= f.text_field :phone, 'Phone' -%>
	<%= f.text_field :fax, 'Fax' -%>
	<%= f.text_field :email, 'Email', nil, class: 'email' -%>
	<%= f.submit_well nil, companies_path, delete_url, delete_confirm -%>
<% end %>

app/views/companies/_show.html.erb
<%#
	company show
%>

<div class='panel panel-default main-panel'>

  <div class='panel-heading'>
    <h3 class='panel-title edit-heading'><%= "#{@company.name} - #{@company.company_type}" -%></h3>
    <%= link_to [:edit, @company], class: "glyphicon glyphicon-pencil edit-heading" do -%><% end -%>
  </div>

  <div class='panel-body'>

    <%= display_basic 'ABN', @company.abn -%>
    <h5><span class='name'>Phone:</span><%= @company.phone -%></h5>
    <h5><span class='name'>Fax:</span><%= @company.fax -%></h5>
    <h5><span class='name'>Email:</span><%= @company.email -%></h5>

  </div>
</div>

<br />

<%= render partial: 'tabs', locals: { show_add_button: true }  -%>

app/views/companies/_show_small.html.erb
<%#
	companies show small
%>

<div class='panel panel-default'>
  <div class='panel-heading'>

    <%#= link_to @company do %>
      <h3 class='panel-title edit-heading'><%= "#{@company.name} - #{@company.company_type}" -%></h3>
    <%# end %>
    <%= link_to [:edit, @company], class: "glyphicon glyphicon-pencil edit-heading" do -%><% end -%>

  </div>
  <div class='panel-body'>

    <%# contacts %>
    <% if @company.person != nil %>
      <% count = 0 %>
      <% @company.person.each do |person| %>
        <% count += 1 %>

        <%#= link_to person do %>
          <h5>
            <span class='name'>Contact Person <%= count -%>:</span><%= "#{person.role} - " if person.role != nil && person.role != ''  -%><%= "#{person.first_name} #{person.last_name}" -%>
          </h5>
        <%# end %>

      <% end -%>
    <% end %>

    <h5><span class='name'>Phone:</span><%= @company.phone -%></h5>
    <h5><span class='name'>Fax:</span><%= @company.fax -%></h5>
    <h5><span class='name'>Email:</span><%= @company.email -%></h5>

    <%# address %>
  	<% if @company.address != nil %>
	    	<h5><span class='name'>Address:</span><%= @company.address.address_str-%></h5>
  	<% end %>

  </div>
</div>

app/views/companies/_tabs.html.erb
<%#
	company tabs

	optional locals: show_add_button
%>

<%
	if defined?(show_add_button) ==nil
		show_add_button = false
	end
%>

<ul class='nav nav-tabs nav-justified'>
  <li class='active'><a data-toggle='tab' href='#people-pane'>Contact People </a></li>
  <li><a data-toggle='tab' href='#address-pane'>Address </a></li>
</ul>

<br />
<br />

<div class="tab-content">

  <div id='people-pane' class='tab-pane fade in active'>

    <% if @company.person != nil %>
      <% @company.person.each do |person| %>
        <% if person.active %>
          <% @person = person %>
          <%= render partial: 'people/show_small' -%>
        <% end %>
      <% end %>
    <% end %>

    <% if show_add_button %>
    	<form action='<%= new_person_path -%>' method='get'>
    		<input type='hidden' name='company_id' value='<%= @company.id -%>' />
    		<input type='submit' value='New Person' class='btn btn-default add-button' />
    	</form>
    <% end %>

  </div>

  <div id='address-pane' class='tab-pane fade'>

    <% puts @company.methods %>

    <% if @company.address != nil %>
      <% @address = @company.address %>
      <%= render partial: 'addresses/show_small' -%>

    <% elsif show_add_button %>
      <form action='<%= new_address_path -%>' method='get'>
        <input type='hidden' name='company_id' value='<%= @company.id -%>' />
        <input type='submit' value='Set Address' class='btn btn-default add-button' />
      </form>
    <% end %>
  </div>

</div>

app/views/companies/edit.html.erb
<%#
	edit company
%>

<% content_for :heading do %>

	<h2>Edit Company - <%= @company.name -%></h2>

<% end -%>

<% content_for :form do %>

	<%= render 'form' -%>

	<br />

	<%= render partial: 'tabs', locals: { show_add_button: true } -%>

<% end %>

app/views/companies/index.html.erb
<%#
  company index
%>
<%# object to get ID for JSON show in layouts/view %>
<% @object = @company %>

<% content_for :heading do %>
  <h2>Companies</h2>
<% end %>

<% content_for :master_list do %>

  <div id='type-button-group' class="btn-group btn-group-justified">
    <%= link_to 'Clients', companies_path(company_type: CompanyType::CLIENT), id: 'clients-button', class: 'btn btn-default' -%>
    <%= link_to 'Printers', companies_path(company_type: CompanyType::PRINT_SUPPLIER), id: 'printers-button', class: 'btn btn-default' -%>
    <%= link_to 'Distributors', companies_path(company_type: CompanyType::DISTRIBUTION_SUPPLIER), id: 'distributors-button', class: 'btn btn-default' -%>
  </div>

  <br />
  <br />

  <% @companies.each do |company| %>
    <a id='<%=company.id%>' data-url='<%=url_for :controller => 'companies', :action => 'show', :id => company.id, :format => 'string' %>' class="list-group-item">
      <h4 class="list-group-item-heading"><%= company.name -%></h4>
      <p class="list-group-item-text"></p>
    </a>
  <% end -%>
<% end %>


<% content_for :after_master_list do %>
  <form id='add-company-form' action='<%= new_company_path -%>'method='get'>
    <button id='add-company-button' type='submit' class='btn btn-default'>Add Company</button>
    <input id='company_type' name='company_type' type='hidden' value='' />
  </form>
<% end %>

<% content_for :js_start do %>
  <script type="text/javascript">

    $(document).ready(function(e) {

      //Make appropriate filter button active
      var activeButtonId = 
      <% if @company_type == CompanyType::PRINT_SUPPLIER %>
        'printers-button';
      <% elsif @company_type == CompanyType::DISTRIBUTION_SUPPLIER %>
        'distributors-button';
      <% else %>
        'clients-button';
      <% end %>
      $('button[data-filter]').removeClass('active')
      $('#' + activeButtonId).addClass('active')

      //Set selected company type for new company
      $('#add-company-form').submit(function(e) {
        var companyType = $('#type-button-group').find('button.active').attr('data-filter');
        $('#company_type').val(companyType);
      });

    });

  </script>
<% end %>

app/views/companies/new.html.erb
<%#
	new company
%>

<% content_for :heading do %>

	<h2>New Company</h2>

<% end -%>

<% content_for :form do %>

	<%= render 'form' -%>

<% end %>