config/routes.rb
Sol::Application.routes.draw do

  devise_for :users, controllers: { :registrations => :registrations, :sessions => :sessions }

  # new users only created by admin
  scope "/admin" do
    resources :users
  end

  resources :jobs
  resources :companies
  resources :people

  resources :addresses
  resources :states
  resources :towns
  resources :postcodes
  resources :countries

  resources :invoices
  resources :invoice_emails

  resources :reports
  resources :job_bag_emails

  resources :print_jobs
  resources :distribute_jobs
  resources :delivery_jobs

  resources :distribute_areas
  resources :delivery_locations

  resources :job_progresses
  
  resources :images
  resources :print_colours

  # for displaying email previews
  get 'invoice_mailer(/:action(/:id(.:format)))' => 'invoice_mailer#:action'

  root 'jobs#index'
end

app/models/delivery_location.rb
class DeliveryLocation < ActiveRecord::Base
	has_one :address

	before_create :activate!

	def summary
		return self.name
	end

	def self.allActive
		return where(active: true)
	end

	def activate!
		self.active = true
	end
end

app/controllers/delivery_locations_controller.rb
class DeliveryLocationsController < ApplicationController

	def index
		@delivery_locations = DeliveryLocation.allActive

		if params[:id] != nil
			@delivery_location = DeliveryLocation.find(params[:id])
		elsif @delivery_locations.count != 0
			@delivery_location = DeliveryLocation.last
		else
			@delivery_location = nil
		end

		@sublayout = 'layouts/view'
	end

	def show
		@delivery_location = DeliveryLocation.find(params[:id])
    @delivery_locations = DeliveryLocation.allActive

		if params[:format] == 'string'
      render partial: 'show', layout: false
    
    else
      @sublayout = 'layouts/view'
      render 'index'
    end
	end

	def new
		@countries = Country.all
		@sublayout = 'layouts/edit'
	end

	def create
		delivery_location = DeliveryLocation.new(post_params)
		delivery_location.save
		redirect_to delivery_location_path(delivery_location)
	end

	def edit
		@countries = Country.all
		@delivery_location = DeliveryLocation.find(params[:id])
		@sublayout = 'layouts/edit'
	end

	def update
		delivery_location = DeliveryLocation.find(params[:id])
		delivery_location.update(post_params)
		redirect_to delivery_location_path(delivery_location)
	end

	def destroy
		delivery_location = DeliveryLocation.find(params[:id])
		location_address = delivery_location.address

		delivery_location.destroy
		
		if location_address
			location_address.destroy
		end

		redirect_to delivery_locations_path
	end

	private
	def post_params
		params.require(:delivery_location).permit(:name, :description)
	end

end

app/views/delivery_locations/_form.html.erb
<%# 
	delivery location form 
%>
<%
	if @delivery_location != nil
		delete_url = delivery_location_path(@delivery_location)
		form_url = delivery_location_path(@delivery_location)
		method = 'patch'

		delete_confirm = "Are you sure you want to permanently delete delivery location #{@delivery_location.name}!?"

	else
		delete_url = nil
		delete_confirm = nil
		form_url = delivery_locations_path
		method = 'post'
	end
%>
<%= bs_form_for :delivery_location, url: form_url, method: method do |f| %>
	<%= f.text_field :name, 'Location Name', nil, required: true -%>
	<%= f.text_field :description, 'Description' -%>
	<%= f.submit_well nil, delivery_locations_path, delete_url, delete_confirm -%>
<% end -%>

app/views/delivery_locations/_show.html.erb
<%#
	delivery locations show
%>

<div class='panel panel-default main-panel'>
  <div class='panel-heading'>

    <h3 class='panel-title edit-heading'><%= "#{@delivery_location.name}" -%></h3>
    <%= link_to [:edit, @delivery_location], class: "glyphicon glyphicon-pencil edit-heading" do -%><% end -%>

  </div>
  <div class='panel-body'>

  	<h5><span class='name'>Description:</span><%= @delivery_location.description -%></h5>

  </div>
</div>

<br />

<%= render partial: 'tabs', locals: { show_add_button: true }  -%>

app/views/delivery_locations/_tabs.html.erb
<%#
	delivery location tabs

	optional locals: show_add_button
%>

<%
	if defined?(show_add_button) ==nil
		show_add_button = false
	end
%>

<ul class='nav nav-tabs nav-justified'>
  <li class='active'><a data-toggle='tab' href='#address-pane'>Address </a></li>
</ul>

<br />

<div class="tab-content">

  <div id='address-pane' class='tab-pane fade in active'>

    <% if @delivery_location.address != nil %>
      <% @address = @delivery_location.address %>
      <%= render 'addresses/show_small' -%>
    <% end %>

    <% if !@delivery_location.address && show_add_button %>
      <form action='<%= new_address_path -%>' method='get'>
        <input type='hidden' name='delivery_location_id' value='<%= @delivery_location.id -%>' />
        <input type='submit' value='Set Address' class='btn btn-default add-button' />
      </form>
    <% end %>

  </div>

</div>

app/views/delivery_locations/edit.html.erb
<%#
	edit delivery location
%>

<% content_for :heading do %>

	<h2>Edit Delivery Location</h2>

<% end -%>

<% content_for :form do %>

	<%= render :partial => 'form'-%>

	<br />

	<%= render partial: 'tabs', locals: { show_add_button: true } -%>

<% end %>

app/views/delivery_locations/index.html.erb
<%#
  delivery locations index
%>

<%# object to get ID for JSON show in layouts/view %>
<% @object = @delivery_location %>

<% content_for :heading do %>

  <h2>Delivery Locations</h2>

<% end %>

<% content_for :master_list do %>

  <% @delivery_locations.each do |location| %>
    <a id='<%=location.id%>' data-url='<%=url_for :controller => 'delivery_locations', :action => 'show', :id => location.id, :format => 'string' %>' class="list-group-item">
      <h4 class="list-group-item-heading"><%= location.name -%></h4>
      <p class="list-group-item-text"></p>
    </a>
  <% end -%>
<% end %>


<% content_for :after_master_list do %>
  <%= button_to new_delivery_location_path, :class => 'btn btn-default', :method => 'get' do -%>
    Add Location
  <% end -%>

<% end %>

app/views/delivery_locations/new.html.erb
<%#
	new delivery location
%>

<% content_for :heading do %>

	<h2>New Delivery Location</h2>

<% end -%>

<% content_for :form do %>
	<%= render 'form' -%>
<% end %>